'use client';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {matchesAssemblySearch,splitIds} from '../../lib/format';
import {confirmDialog,toast,uid} from '../shared/common';

export function AssemblyLibrary({data,setData}:any){
 const blank=(type='Sub Assembly')=>({id:uid('tpl'),partNumber:'',description:'',type,defaultQty:1,hoursEach:1,testRequired:false,testHours:0,inspectionRequired:false,inspectionHours:0,shippingRequired:false,shippingHours:0,testReturnDateTime:'',inspectionAssignedTo:'',shippingAssignedTo:'',inspectionManualStartDate:'',shippingManualStartDate:'',inspectionComplete:false,shippingComplete:false,maxTopPercentWhenSubHeld:80,defaultDependsOn:'',notes:'',archived:false});
 const rows=data.assemblyTemplates||[];
 const [showArchived,setShowArchived]=useState(false);
 const [filter,setFilter]=useState('All');
 const [search,setSearch]=useState('');
 const [selectedId,setSelectedId]=useState(rows[0]?.id||'');
 const visibleRows=rows.filter((r:any)=>showArchived||!r.archived).filter((r:any)=>filter==='All'||r.type===filter).filter((r:any)=>matchesAssemblySearch(r,search));
 const selected=rows.find((r:any)=>r.id===selectedId)||visibleRows[0]||rows[0];
 useEffect(()=>{if(selected&&!selectedId)setSelectedId(selected.id)},[selected,selectedId]);
 function changeById(id:string,k:string,v:any){setData((d:any)=>({...d,assemblyTemplates:d.assemblyTemplates.map((r:any)=>r.id===id?{...r,[k]:v}:r)}))}
 function patchItem(id:string,patch:any){setData((d:any)=>({...d,assemblyTemplates:d.assemblyTemplates.map((r:any)=>r.id===id?{...r,...patch}:r)}))}
 function add(type:string){const row=blank(type);setData((d:any)=>({...d,assemblyTemplates:[...d.assemblyTemplates,row]}));setSelectedId(row.id)}
 function duplicate(id:string){const item=rows.find((r:any)=>r.id===id);if(!item)return;const copy={...item,id:uid('tpl'),partNumber:(item.partNumber||'')+' COPY',description:(item.description||'')+' Copy',archived:false,notes:item.notes||''};setData((d:any)=>({...d,assemblyTemplates:[...d.assemblyTemplates,copy]}));setSelectedId(copy.id)}
 function activeUsage(id:string){const activeProjectIds=new Set((data.projects||[]).filter((p:any)=>!['Complete','Cancelled'].includes(p.status)).map((p:any)=>p.id));return (data.projectAssemblies||[]).filter((a:any)=>a.templateId===id&&activeProjectIds.has(a.projectId))}
 function usageProjectList(usages:any[]){const ids=[...new Set(usages.map((u:any)=>u.projectId))];return ids.map((pid:string)=>{const p=(data.projects||[]).find((x:any)=>x.id===pid);return p?.projectId||p?.name||pid}).join(', ')}
 async function archive(id:string){const item=rows.find((r:any)=>r.id===id);if(!item)return;const action=item.archived?'unarchive':'archive';if(!await confirmDialog(`${action[0].toUpperCase()+action.slice(1)} ${item.partNumber||'this assembly'}?`))return;patchItem(id,{archived:!item.archived,archivedAt:!item.archived?new Date().toISOString():''})}
 async function del(id:string){const item=rows.find((r:any)=>r.id===id);if(!item)return;const usages=activeUsage(id);if(usages.length){toast(`Cannot delete this library item because it is used on active project(s): ${usageProjectList(usages)}. Archive it instead if you want to hide it from future use.`,'bad');return;}if(!await confirmDialog(`Delete ${item.partNumber||'this library item'}? This is only allowed because it is not used on an active project.`))return;setData((d:any)=>({...d,assemblyTemplates:d.assemblyTemplates.filter((r:any)=>r.id!==id).map((r:any)=>({...r,defaultDependsOn:splitIds(r.defaultDependsOn).filter((x:string)=>x!==id).join(',')}))}));if(selectedId===id)setSelectedId('')}
 function whereUsed(id:string){const usages=activeUsage(id);if(!usages.length){toast('This assembly is not used on any active project.','info');return;}toast('Used on active project(s): '+usageProjectList(usages),'info')}
 function subList(top:any){return splitIds(top.defaultDependsOn).map((id:string,idx:number)=>({id,idx,item:rows.find((r:any)=>r.id===id)})).filter((x:any)=>x.item)}
 const topCount=rows.filter((r:any)=>r.type==='Top Level Assembly'&&!r.archived).length;
 const subCount=rows.filter((r:any)=>r.type==='Sub Assembly'&&!r.archived).length;
 return <div className="libraryWorkspace">
   <div className="card libraryHeader"><div><h2>Assembly Library</h2><p className="muted">Reusable scheduling templates only. Select an assembly on the left, edit it on the right, and build top-level sub assembly trees without leaving the page.</p></div><div className="libraryStats"><span><b>{topCount}</b> Top Level</span><span><b>{subCount}</b> Subs</span><span><b>{rows.filter((r:any)=>r.archived).length}</b> Archived</span></div></div>
   <div className="card libraryListPanel"><div className="libraryTools"><input className="largeInput" placeholder="Search part #, description, notes..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="largeInput" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Top Level Assembly</option><option>Sub Assembly</option></select><label className="checkLine"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Show archived</label></div><div className="actions"><button className="btn primary" onClick={()=>add('Top Level Assembly')}>Add Top Level</button><button className="btn" onClick={()=>add('Sub Assembly')}>Add Sub</button></div><div className="librarySelectableList">{visibleRows.length===0&&<p className="muted">No matching assemblies.</p>}{visibleRows.map((r:any)=>{const used=activeUsage(r.id).length;const subs=r.type==='Top Level Assembly'?splitIds(r.defaultDependsOn).length:0;return <button key={r.id} className={selected?.id===r.id?'librarySelect activeLibrarySelect':'librarySelect'} onClick={()=>setSelectedId(r.id)}><div><b>{r.partNumber||'New Assembly'}</b>{r.archived&&<span className="pill warn">Archived</span>}</div><span>{r.description||'No description'}</span><small>{r.type}{r.type==='Top Level Assembly'?` • ${subs} subs`:''}{used?` • used ${used}`:''}</small></button>})}</div></div>
   <div className="card libraryEditorPanel">{selected?<AssemblyEditor item={selected} rows={rows} data={data} changeById={changeById} patchItem={patchItem} duplicate={duplicate} archive={archive} del={del} whereUsed={whereUsed} onOpenSub={(id:string)=>setSelectedId(id)}/>:<p className="muted">Select or add an assembly to edit.</p>}</div>
 </div>
}

export function AssemblyEditor({item,rows,data,changeById,patchItem,duplicate,archive,del,whereUsed,onOpenSub}:any){
 const subs=rows.filter((r:any)=>r.type==='Sub Assembly'&&!r.archived);
 const [subToAdd,setSubToAdd]=useState('');
 const [subSearch,setSubSearch]=useState('');
 const linkedIds=splitIds(item.defaultDependsOn);
 useEffect(()=>{if(!subToAdd&&subs[0])setSubToAdd(subs[0].id)},[subToAdd,subs]);
 const filteredSubs=subs.filter((s:any)=>matchesAssemblySearch(s,subSearch));
 const selectedSub=subs.find((s:any)=>s.id===subToAdd);
 const visibleSubs=selectedSub&&!filteredSubs.some((s:any)=>s.id===selectedSub.id)?[selectedSub,...filteredSubs]:filteredSubs;
 function setSubs(ids:string[]){changeById(item.id,'defaultDependsOn',ids.join(','))}
 function addSub(){const id=subToAdd||subs[0]?.id;if(!id)return;setSubs([...linkedIds,id]);setSubToAdd('')}
 function removeSubAt(idx:number){setSubs(linkedIds.filter((_:string,i:number)=>i!==idx))}
 function moveSubAt(idx:number,dir:number){const next=[...linkedIds];const ni=idx+dir;if(idx<0||ni<0||ni>=next.length)return;[next[idx],next[ni]]=[next[ni],next[idx]];setSubs(next)}
 const req=(label:string,reqKey:string,hoursKey:string)=><div className="libraryReq"><label><input type="checkbox" checked={!!item[reqKey]} onChange={e=>changeById(item.id,reqKey,e.target.checked)}/> {label}</label><input className="largeInput" type="number" min="0" value={item[hoursKey]||0} onChange={e=>changeById(item.id,hoursKey,Number(e.target.value)||0)}/><span className="muted">hrs</span></div>;
 const linked=linkedIds.map((id:string,idx:number)=>({id,idx,item:rows.find((x:any)=>x.id===id)})).filter((x:any)=>x.item);
 const usage=(data.projectAssemblies||[]).filter((a:any)=>a.templateId===item.id);
 return <div className="assemblyEditor"><div className="editorTitle"><div><h2>{item.partNumber||'New Assembly'}</h2><p className="muted">{item.type}{item.archived?' • Archived':''}</p></div><div className="actions"><button className="btn" onClick={()=>duplicate(item.id)}>Duplicate</button><button className="btn" onClick={()=>whereUsed(item.id)}>Where Used</button><button className="btn" onClick={()=>archive(item.id)}>{item.archived?'Unarchive':'Archive'}</button><button className="btn danger" onClick={()=>del(item.id)}>Delete</button></div></div>
   <div className="editorSections"><section><h3>Basic Info</h3><div className="editorGrid"><div className="field"><label>Part #</label><input className="largeInput" value={item.partNumber||''} onChange={e=>changeById(item.id,'partNumber',e.target.value)}/></div><div className="field wide"><label>Description</label><input className="largeInput" value={item.description||''} onChange={e=>changeById(item.id,'description',e.target.value)}/></div><div className="field"><label>Type</label><select className="largeInput" value={item.type} onChange={e=>changeById(item.id,'type',e.target.value)}><option>Top Level Assembly</option><option>Sub Assembly</option></select></div><div className="field"><label>Default Qty</label><input className="largeInput" type="number" min="1" value={item.defaultQty||1} onChange={e=>changeById(item.id,'defaultQty',Number(e.target.value)||1)}/></div><div className="field"><label>Build Hours Each</label><input className="largeInput" type="number" min="0" value={item.hoursEach||0} onChange={e=>changeById(item.id,'hoursEach',Number(e.target.value)||0)}/></div>{item.type==='Top Level Assembly'&&<div className="field"><label>Top % If Sub Held</label><input className="largeInput" type="number" min="0" max="100" value={item.maxTopPercentWhenSubHeld||80} onChange={e=>changeById(item.id,'maxTopPercentWhenSubHeld',Number(e.target.value)||0)}/></div>}<div className="field full"><label>Notes</label><textarea className="largeInput" value={item.notes||''} onChange={e=>changeById(item.id,'notes',e.target.value)}/></div></div></section>
   <section><h3>Schedule Requirements</h3><div className="reqGrid">{req('Test Required','testRequired','testHours')}{req('Inspection Required','inspectionRequired','inspectionHours')}{req('Shipping Required','shippingRequired','shippingHours')}</div></section>
   {item.type==='Top Level Assembly'&&<section><h3>Sub Assembly Tree Builder</h3><p className="muted">Add sub assemblies to this top level. The same sub assembly can be added multiple times when a build needs repeated units. Sub details are shown read-only here — use Edit sub to change a sub (changes apply everywhere it is used).</p><div className="treeBuilderAdd"><input className="largeInput" value={subSearch} placeholder="Search sub part # / description..." onChange={e=>setSubSearch(e.target.value)}/><select className="largeInput" value={subToAdd} onChange={e=>setSubToAdd(e.target.value)}>{visibleSubs.map((s:any)=><option key={s.id} value={s.id}>{s.partNumber||'New Sub'} — {s.description||'No description'}</option>)}</select><button className="btn primary" disabled={!subs.length||!visibleSubs.length} onClick={addSub}>Add Sub Assembly</button></div><div className="treeBuilderList">{linked.length===0&&<p className="muted">No subs assigned to this top level yet.</p>}{linked.map(({item:s,idx}:any)=><div className="treeBuilderRow" key={s.id+'-'+idx}><div className="treeHandle">↳ #{idx+1}</div><div className="treeSubFields treeSubReadonly"><b>{s.partNumber||'New Sub'}</b><span>{s.description||'No description'}</span><small>{s.hoursEach||0} hrs each · qty {s.defaultQty||1}</small></div><div className="treeRowActions"><button className="mini" onClick={()=>moveSubAt(idx,-1)}>↑</button><button className="mini" onClick={()=>moveSubAt(idx,1)}>↓</button><button className="mini" title="Open this sub in the editor. Edits to a sub apply everywhere it is used." onClick={()=>onOpenSub&&onOpenSub(s.id)}>Edit sub</button><button className="mini danger" onClick={()=>removeSubAt(idx)}>Remove</button></div></div>)}</div></section>}
   <section><h3>Usage / Safety</h3><p className="muted">Used on {usage.length} project assembly item{usage.length===1?'':'s'}. Delete is blocked when this item is used on active projects; archive it to hide from future project adds.</p></section>
   </div></div>
}
